#
#--------------------------------------------------------------------------
# Image Setup (in test)
#--------------------------------------------------------------------------
#

FROM centos
RUN yum install wget 

LABEL maintainer="zhang fan <my_mail@mail.com>"

#
#--------------------------------------------------------------------------
# Software's Installation
#--------------------------------------------------------------------------
#

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm


